name = "workers-getting-started"
main = "src/index.ts"
compatibility_date = "2025-03-11"

[observability]
enabled = true

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CACHE"
id = "ea30a4df573e4533ba5dfece22c6a7b9"
