-- Migration number: 0003 	 2025-03-12T21:24:05.465Z

-- alter table to autogenerated id for movies

-- Migration number: 0003 	 2025-03-12T21:24:05.465Z

-- Create a new table with the desired schema
CREATE TABLE new_movies (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title VARCHAR(255) NOT NULL,
	release_date DATE NOT NULL,
	rating INTEGER NOT NULL
);

-- Copy data from the old table to the new table
INSERT INTO new_movies
	(id, title, release_date, rating)
SELECT id, title, release_date, rating
	FROM movies;

-- Drop the old table
DROP TABLE movies;

-- Rename the new table to the old table's name
ALTER TABLE new_movies RENAME TO movies;


